[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity="0.10"
async-trait="0.1"
azure_core="0.1"

[dependencies.tokio]
version="1"
features = ["full"]
