[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity="0.10"
async-trait="0.1"
azure_core="0.1"
reqwest="0.11"
http="0.2"
serde="1"
openssl="0.10"
base64="0.13"

[dependencies.jwt]
features=["openssl"]
version="0.16"

[dependencies.uuid]
features=["v4"]
version="0.8"

[dependencies.tokio]
version="1"
features = ["full"]
